import "./globals.css";
import { FilterBar, FilterSide } from "@/sections";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <FilterBar title="Products" />
          <div className="grid grid-cols-12 gap-6">
            <div className="col-span-2">
              <FilterSide />
            </div>
            <div className="col-span-10">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
